name: game_services_firebase_auth
description: This plugin make some FirebaseAuth features available with GameCenter on iOS and PlayGames on Android
version: 0.4.0
homepage: https://github.com/jgrandchavin/game_services_firebase_auth.git
repository: https://github.com/jgrandchavin/game_services_firebase_auth.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter:
    sdk: flutter



dev_dependencies:
  flutter_test:
    sdk: flutter

false_secrets:
  - /example/android/app/google-services.json

flutter:
  plugin:
    platforms:
      android:
        package: dev.juliengrandchavin.game_services_firebase_auth
        pluginClass: GameServicesFirebaseAuthPlugin
      ios:
        pluginClass: GameServicesFirebaseAuthPlugin